name: Create and publish a Docker image

on:
  pull_request:
    branches: 
      - development
    types: [closed]

# on:
#   push:
#     branches: 
#       - development

# on:
#   push:
#     tags:
#       - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_HUB_REPO: react-app
  LOCAL_DOCKER_UNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push-to-registries:
    if: ${{ github.event.pull_request.merged }}
    name: Build Docker image and push to multiple registries
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Set environmental variables"
        run: echo "TAG=$LOCAL_DOCKER_UNAME/$DOCKER_HUB_REPO:" >> $GITHUB_ENV
      
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}            
          # flavor: |
          #   latest=false
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=development
          #type=ref,event=branch
           
      - name: Print metadata tags
        run: echo "${{ steps.meta.outputs.tags }}"

      - name: Print metadata labels
        run: echo "${{ steps.meta.outputs.labels }}"

      - name: Get version from package.json
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      # - name: Use version variable
      #   run: echo "${{ env.VERSION }}"

      # - name: Print own tagname
      #   run: echo "${{ env.TAG }}${{ env.VERSION }}"

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          #tags: ${{ env.TAG }}${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}