name: Environment test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
      - name: print env
        run: |
          touch .env
          echo "$REACT_APP_1" >> .env
          cat .env
        env:
          REACT_APP_1: ${{ secrets.REACT_APP_1 }}
