name: Test release link action

on:
  push:
   # types: [published]

jobs:
  get-link:
    name: Get link to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Print link 
        run: echo ${{ steps.get_release.outputs.upload_url }}
